# -*- coding: utf-8 -*-
"""Employee data analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vBD66-rKhzMaMneaREEJCM3qyl37pE_v

# Python Code for Data Preprocessing & Analysis
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("myexcel.csv")

df

"""# Preprocessing:"""

df["height"] = np.random.randint(150, 181, size=len(df))
print(df["height"].describe())  # Check the new height column stats
df.to_csv("cleaned_dataset.csv", index=False)

# 1. Determine the distribution of employees across each team and calculate the percentage split relative to the total number of employees.

team_dist = df['Team'].value_counts()

team_dist_perct = (team_dist/len(df))*100

team_stats = pd.DataFrame({'Employee Count':team_dist,
                           'Percentage':team_dist_perct})
print(team_stats)

# Visualization

plt.figure(figsize=(8,8))
plt.pie(team_dist_perct, labels=team_dist.index, autopct='%1.1f%%')
plt.title('Percentage Split of Employees Across Teams')
plt.show()

# 2.Segregate employees based on their positions within the company.

position_dist = df['Position'].value_counts()

position_df = pd.DataFrame({'Position': position_dist.index, 'Count': position_dist.values})
print(position_df)

# Visualisation

plt.figure(figsize=(6,5))
sns.barplot(position_df,x='Position',y='Count',hue='Count', palette='coolwarm')
plt.xlabel('Position of Employees')
plt.ylabel('Number of Employees')
plt.title('Employee Distribution across Position')

# 3. Identify the predominant age group among employees.

bins = [18,25,35,45,55,65]
labels = ['18-25','26-35','36-45','46-55','56-65']

df['Age Group'] = pd.cut(df['Age'],bins=bins, labels=labels, right=True)
age_grp_disbn = df['Age Group'].value_counts()


df_age_grp_disbn = pd.DataFrame({'Age Group':age_grp_disbn.index, 'Count': age_grp_disbn.values})
print(age_grp_disbn)

# Visualization for age across Age Group

plt.figure(figsize=(6,5))
sns.barplot(x = age_grp_disbn.index, y= age_grp_disbn.values, hue=age_grp_disbn.values, palette='bright')
plt.xlabel('Age Group of Employees')
plt.ylabel('Count in the Age group')
plt.title('Age Distribution across Age Group')

# 4. Discover which team and position have the highest salary expenditure.

# finding the Highest Salary Expenditure per Team

team_sal_expen = df.groupby('Team')['Salary'].sum().sort_values(ascending=False)

#Display the top 5 teams
print(team_sal_expen.head())

# Visualization for the Highest Salary Expenditure per Team

plt.figure(figsize=(11,5))
sns.barplot(x=team_sal_expen.head().index,y=team_sal_expen.head().values,hue=team_sal_expen.head().values, palette="coolwarm")
plt.xlabel("Team")
plt.ylabel("Total Salary Expenditure")
plt.title("Total Salary Expenditure by Team")
plt.show()

# finding the Salary Expenditure per Position

position_sal_expen = df.groupby('Position')['Salary'].sum().sort_values(ascending=False)

#Display the top 5 position
print(position_sal_expen.head())

# Visualization for the Highest Salary Expenditure per Position


plt.figure(figsize=(10,7))
df.groupby("Position")["Salary"].sum().plot(kind="pie", autopct="%1.1f%%", cmap="coolwarm", startangle=90)
plt.title("Salary Expenditure Distribution by Position")
plt.ylabel("")
plt.show()

#5. Investigate if there's any correlation between age and salary, and represent it visually.


# Checking Correlation

correlation = df["Age"].corr(df["Salary"])
print(f"Correlation between Age and Salary: {correlation}")

# Scatter Plot for visualizing relationship between age and Salary

plt.figure(figsize=(8,6))
sns.scatterplot(x=df["Age"], y=df["Salary"], color="blue", alpha=0.6)

plt.xlabel("Age")
plt.ylabel("Salary")
plt.title("Scatter Plot of Age vs. Salary")
plt.show()

"""# Insights from the Data Analysis

# Salary Distribution Across Teams & Positions

 #Key Finding:

1.The highest salary expenditure is seen in the Cleveland Cavaliers and the C role.
2.Certain teams have a higher proportion of employees but contribute less to the overall salary expenditure, suggesting pay disparity across departments.
3.Senior-level roles have significantly higher salaries compared to entry-level roles.

- Actionable Insight: The company could evaluate salary structures to ensure fair compensation across teams.

#Correlation Between Age & Salary

Key Finding:

1.The correlation between Age and Salary is 0.20, which indicates a weak positive relationship.
2.While older employees generally earn more, age alone is not a strong factor in salary determination.
3.Other factors like experience, role, and education might have a stronger impact.

 Actionable Insight: The company could focus on performance-based pay rather than tenure-based increments.

#Employee Distribution by Age Group & Position

Key Finding:

1.The majority of employees fall within the 26-35 category.
2.Certain age groups dominate specific job roles, indicating possible career progression trends.
3.The presence of few senior employees in high-paying roles suggests limited upward mobility.

Actionable Insight: The company could introduce mentorship programs to prepare mid-level employees for leadership roles.
*
"""

